# Full command list of cypress github actions:
#   https://github.com/cypress-io/github-action#cypress-iogithub-action--

name: End to end tests
on:
  # To run tests on the push event of a specific branch:
  # push:
  #   branches:
  #     - vimusds/cypress-debug-download
  schedule:
    # runs tests every day at 12am ET (4am UTC):
    - cron: '0 4 * * *'
jobs:
  nightly:
    runs-on: ubuntu-20.04
    env:
      working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress nightly tests ðŸŒƒ
        uses: cypress-io/github-action@v2
        with:
          working-directory: ${{env.working-directory}}
          start: npm start
          wait-on: 'http://localhost:8000'
          # To run only specific spec/tests:
          # spec: cypress/e2e/downloadPacket.spec.js
